language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge;
  - conda install tectonic
scripts:
  - if [ -n "$TRAVIS_TAG" ]; then tectonic cs/ethan-resume.xtx -p; fi; # If this is tagged, build the latex and the pdf to be released.
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - cs/ethan_resume.pdf
    skip_cleanup: true
    on:
      tags: true
