before_deploy:
  - if [ -n "$TRAVIS_TAG" ]; then ./build_pdf.sh; fi; # If this is tagged, build the latex and the pdf to be released.
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - cs/ehtan_resume.pdf
    skip_cleanup: true
    on:
      tags: true
